apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
spec:
  replicas: 10
  selector: 
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec: 
      containers:
      - name: nginx-deploy
        image: nginx
        ports:
        - containerPort: 80