trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  SQLserver: 'nextopssqlt19'
  DatabaseName: 'mhdb'
  SQLserverfqdn: 'nextopssqlt19.database.windows.net'

stages: 
- stage: Build
  displayName: AKS Build Stage 
  jobs:
  - job: Build 
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
        KeyVaultName: 'nextopsakvt20'
        SecretsFilter: '*'
        RunAsPreJob: true
     
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(build.sourcesdirectory)/env'
        targetFiles: 'main.tf'
        encoding: 'auto'
        tokenPattern: 'rm'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
    
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'    
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(build.sourcesdirectory)/env'
        backendServiceArm: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
        backendAzureRmResourceGroupName: 'NextOps'
        backendAzureRmStorageAccountName: 'nextopstfsat20'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'AKS/aks.tfstate'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(build.sourcesdirectory)/env'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
    
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(build.sourcesdirectory)/src/MyHealth.Web'
        targetFiles: 'appsettings.json'
        encoding: 'auto'
        tokenPattern: 'rm'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
    
    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
        azureContainerRegistry: '{"loginServer":"nextopsacr19.azurecr.io", "id" : "/subscriptions/a355c32e-4a22-4b05-aab4-be236850fa6e/resourceGroups/AKSRG19/providers/Microsoft.ContainerRegistry/registries/nextopsacr19"}'
        dockerComposeFile: '$(build.sourcesdirectory)/docker-compose.ci.build.yml'
        dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
        projectName: 'aksproject'
        action: 'Run services'
        detached: false
    
    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
        azureContainerRegistry: '{"loginServer":"nextopsacr19.azurecr.io", "id" : "/subscriptions/a355c32e-4a22-4b05-aab4-be236850fa6e/resourceGroups/AKSRG19/providers/Microsoft.ContainerRegistry/registries/nextopsacr19"}'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: '''DOCKER_BUILD_SOURCE='''
        projectName: 'aksproject'
        action: 'Build services'
    
    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
        azureContainerRegistry: '{"loginServer":"nextopsacr19.azurecr.io", "id" : "/subscriptions/a355c32e-4a22-4b05-aab4-be236850fa6e/resourceGroups/AKSRG19/providers/Microsoft.ContainerRegistry/registries/nextopsacr19"}'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: '''DOCKER_BUILD_SOURCE='''
        projectName: 'aksproject'
        action: 'Push services'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: |
          **/mhc-aks.yaml
          **/*.dacpac
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DB
  displayName: DB Stage 
  dependsOn: Build 
  condition: succeeded() 
  jobs:
    - deployment: DB 
      displayName: 'DB Deployment'
      environment: 'prod'
      pool:
        vmImage: 'windows-2019'
      strategy: 
       runOnce:
         deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
              KeyVaultName: 'nextopsakvt20'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: SqlAzureDacpacDeployment@1
            inputs:
              azureSubscription: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
              AuthenticationType: 'server'
              ServerName: '$(SQLserverfqdn)'
              DatabaseName: '$(DatabaseName)'
              SqlUsername: '$(SQLUser)'
              SqlPassword: '$(SQLPass)'
              deployType: 'DacpacTask'
              DeploymentAction: 'Publish'
              DacpacFile: '$(pipeline.workspace)/**/*.dacpac'
              IpDetectionMethod: 'IPAddressRange'
              StartIpAddress: '0.0.0.0'
              EndIpAddress: '255.255.255.255'

- stage: AKS
  displayName: AKS Stage 
  dependsOn: DB 
  condition: succeeded() 
  jobs:
    - deployment: AKS 
      displayName: 'AKS Deployment'
      environment: 'prod'
      strategy: 
       runOnce:
         deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
              azureResourceGroup: 'AKSRG19'
              kubernetesCluster: 'nextopsaks19'
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(pipeline.workspace)/drop/mhc-aks.yaml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
              azureSubscriptionEndpointForSecrets: 'Pay-As-You-Go(a355c32e-4a22-4b05-aab4-be236850fa6e)'
              azureContainerRegistry: 'nextopsacr19.azurecr.io'
              secretName: 'acrsecret'