- name: create user with plain text pass
  hosts: lservers
  remote_user: root
  vars:
    secret: Secure*123 

  tasks:
  - name: create a new user account 
    user:
      name: user7
      password: "{{ secret | password_hash('sha512') }}"
      state: present