- name: create user with plain text pass
  hosts: lservers
  remote_user: root 

  tasks:
  - name: create a new user account 
    user:
      name: user5
      password: Secure*123
      state: present