apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: location
              labelSelector: 
                matchExpressions:
                  - key: app
                    operator: In 
                    values:
                    - nginx 