- name: vars example1
  hosts: lservers
  remote_user: root
  vars:
    Course: DevOps
    Module: Ansible 

  tasks:
  - name: print the variable values into a text file on the remote machines
    shell: echo "I have enrolled in {{ Course }} course and i am currently in {{ Module }} module" > /home/charan/vars_example1.txt