apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev-team
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: nginx-pod  # This label matches the network policy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80