apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec: 
      containers:
      - name: nginx-deploy
        image: nginx:1.26.2
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx-service 
spec:  
  type: ClusterIP
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-deploy