apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd-deploy
  template:
    metadata:
      labels:
        app: httpd-deploy
    spec:
      containers:
      - name: httpd-deploy
        image: httpd:2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: httpd-service
spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: httpd-deploy 