apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-np-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-np-deploy
  template:
    metadata:
      labels:
        app: nginx-np-deploy
    spec:
      containers:
      - name: nginx-np-deploy
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-np-service
spec: 
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-np-deploy