apiVersion: v1
kind: Secret 
metadata: 
  name: mongodb-secret
type: Opaque
data: 
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4xMjM0NQ==
  mongo-web-username: d2ViYWRtaW4=
  mongo-web-password: d2ViYWRtaW4xMjM0NQ==